2025-09-07 23:39:22,362 INFO [app] Logging system initialized
2025-09-07 23:39:22,362 INFO [app] Log level: INFO
2025-09-07 23:39:22,362 INFO [app] Log file: /Users/genacvali/Documents/crystall-budget-3/./logs/crystalbudget.log
2025-09-07 23:45:20,338 INFO [app] Logging system initialized
2025-09-07 23:45:20,338 INFO [app] Log level: INFO
2025-09-07 23:45:20,338 INFO [app] Log file: /Users/genacvali/Documents/crystall-budget-3/./logs/crystalbudget.log
2025-09-07 23:54:05,596 INFO [app] Logging system initialized
2025-09-07 23:54:05,597 INFO [app] Log level: INFO
2025-09-07 23:54:05,597 INFO [app] Log file: /Users/genacvali/Documents/crystall-budget-3/logs/crystalbudget.log
2025-09-07 23:54:05,616 INFO [app] Created savings_goals table
2025-09-07 23:54:05,617 INFO [app] Created shared_budgets table
2025-09-07 23:54:05,617 INFO [app] Created shared_budget_members table
2025-09-07 23:54:05,617 INFO [app] Created exchange_rates table
2025-09-07 23:54:05,618 INFO [app] New tables migration completed successfully
2025-09-07 23:54:23,442 INFO [app] Logging system initialized
2025-09-07 23:54:23,442 INFO [app] Log level: INFO
2025-09-07 23:54:23,442 INFO [app] Log file: /Users/genacvali/Documents/crystall-budget-3/logs/crystalbudget.log
2025-09-07 23:54:23,453 INFO [app] New tables migration completed successfully
2025-09-07 23:54:47,886 INFO [app] Logging system initialized
2025-09-07 23:54:47,886 INFO [app] Log level: INFO
2025-09-07 23:54:47,886 INFO [app] Log file: /Users/genacvali/Documents/crystall-budget-3/logs/crystalbudget.log
2025-09-07 23:54:47,895 INFO [app] New tables migration completed successfully
2025-09-07 23:55:05,305 INFO [app] Logging system initialized
2025-09-07 23:55:05,305 INFO [app] Log level: INFO
2025-09-07 23:55:05,305 INFO [app] Log file: /Users/genacvali/Documents/crystall-budget-3/logs/crystalbudget.log
2025-09-07 23:55:05,314 INFO [app] New tables migration completed successfully
2025-09-07 23:55:05,323 INFO [werkzeug] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://10.17.211.208:5001
2025-09-07 23:55:05,323 INFO [werkzeug] [33mPress CTRL+C to quit[0m
2025-09-07 23:55:12,690 INFO [werkzeug] 127.0.0.1 - - [07/Sep/2025 23:55:12] "[32mGET / HTTP/1.1[0m" 302 -
2025-09-09 10:32:32,937 INFO [app] Logging system initialized
2025-09-09 10:32:32,937 INFO [app] Log level: INFO
2025-09-09 10:32:32,937 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 10:32:36,354 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:32:37,896 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:32:38,582 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:32:39,364 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:33:28,862 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:34:08,578 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:34:14,200 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:34:15,711 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 10:53:13,862 INFO [app] Logging system initialized
2025-09-09 10:53:13,863 INFO [app] Log level: INFO
2025-09-09 10:53:13,863 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 10:53:25,263 ERROR [app] Exception on /categories [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1439, in categories
    return render_template("categories.html",
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/admin/crystall-budget/templates/categories.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/admin/crystall-budget/templates/base.html", line 156, in top-level template code
    <a class="dropdown-item nav-link-modern" href="{{ url_for('account_page') }}">
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'account_page'. Did you mean 'account' instead?
2025-09-09 10:53:25,269 ERROR [app] 500 Internal Server Error: http://localhost:5000/categories - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 10:53:27,315 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1155, in dashboard
    return render_template(
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/admin/crystall-budget/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/admin/crystall-budget/templates/base.html", line 156, in top-level template code
    <a class="dropdown-item nav-link-modern" href="{{ url_for('account_page') }}">
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'account_page'. Did you mean 'account' instead?
2025-09-09 10:53:27,317 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 10:59:57,928 INFO [app] Logging system initialized
2025-09-09 10:59:57,929 INFO [app] Log level: INFO
2025-09-09 10:59:57,929 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:00:10,767 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:00:12,574 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:00:13,262 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:01:03,968 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:09:04,200 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:09:10,005 INFO [app] POST request to categories_add from 127.0.0.1
2025-09-09 11:09:10,341 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:09:13,051 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:09:14,186 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:09:15,309 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:09:16,413 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:10:15,480 INFO [app] Logging system initialized
2025-09-09 11:10:15,480 INFO [app] Log level: INFO
2025-09-09 11:10:15,480 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:10:19,115 ERROR [app] Exception on /categories [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1422, in categories
    rows = conn.execute(
sqlite3.OperationalError: no such table: categories
2025-09-09 11:10:19,119 ERROR [app] 500 Internal Server Error: http://localhost:5000/categories - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:10:20,400 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1006, in dashboard
    categories = conn.execute(
sqlite3.OperationalError: no such table: categories
2025-09-09 11:10:20,402 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:10:54,053 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1006, in dashboard
    categories = conn.execute(
sqlite3.OperationalError: no such table: categories
2025-09-09 11:10:54,053 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:10:55,747 ERROR [app] Exception on /categories [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1422, in categories
    rows = conn.execute(
sqlite3.OperationalError: no such table: categories
2025-09-09 11:10:55,747 ERROR [app] 500 Internal Server Error: http://localhost:5000/categories - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:10:56,194 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1006, in dashboard
    categories = conn.execute(
sqlite3.OperationalError: no such table: categories
2025-09-09 11:10:56,195 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:11:29,241 INFO [app] Logging system initialized
2025-09-09 11:11:29,242 INFO [app] Log level: INFO
2025-09-09 11:11:29,242 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:12:27,632 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1006, in dashboard
    categories = conn.execute(
sqlite3.OperationalError: no such table: categories
2025-09-09 11:12:27,634 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:13:30,631 INFO [app] Logging system initialized
2025-09-09 11:13:30,631 INFO [app] Log level: INFO
2025-09-09 11:13:30,631 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:13:33,992 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1006, in dashboard
    categories = conn.execute(
sqlite3.OperationalError: no such table: categories
2025-09-09 11:13:33,993 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:14:42,132 INFO [app] Logging system initialized
2025-09-09 11:14:42,132 INFO [app] Log level: INFO
2025-09-09 11:14:42,132 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:22:54,561 INFO [app] Logging system initialized
2025-09-09 11:22:54,562 INFO [app] Log level: INFO
2025-09-09 11:22:54,562 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:22:58,550 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1011, in dashboard
    income_sum = conn.execute(
sqlite3.OperationalError: no such table: income_daily
2025-09-09 11:22:58,553 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:23:00,078 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1011, in dashboard
    income_sum = conn.execute(
sqlite3.OperationalError: no such table: income_daily
2025-09-09 11:23:00,080 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:23:00,579 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1011, in dashboard
    income_sum = conn.execute(
sqlite3.OperationalError: no such table: income_daily
2025-09-09 11:23:00,580 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:23:00,738 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1011, in dashboard
    income_sum = conn.execute(
sqlite3.OperationalError: no such table: income_daily
2025-09-09 11:23:00,739 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:23:01,378 ERROR [app] Exception on /categories [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1422, in categories
    rows = conn.execute(
sqlite3.OperationalError: no such column: category_type
2025-09-09 11:23:01,378 ERROR [app] 500 Internal Server Error: http://localhost:5000/categories - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:23:02,153 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1011, in dashboard
    income_sum = conn.execute(
sqlite3.OperationalError: no such table: income_daily
2025-09-09 11:23:02,154 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:23:02,895 ERROR [app] Exception on /categories [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1422, in categories
    rows = conn.execute(
sqlite3.OperationalError: no such column: category_type
2025-09-09 11:23:02,895 ERROR [app] 500 Internal Server Error: http://localhost:5000/categories - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:23:03,967 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:23:04,963 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1011, in dashboard
    income_sum = conn.execute(
sqlite3.OperationalError: no such table: income_daily
2025-09-09 11:23:04,963 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:26:05,283 INFO [app] Logging system initialized
2025-09-09 11:26:05,284 INFO [app] Log level: INFO
2025-09-09 11:26:05,284 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:26:08,549 ERROR [app] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1021, in dashboard
    expenses_rows = conn.execute(
sqlite3.OperationalError: no such column: e.note
2025-09-09 11:26:08,552 ERROR [app] 500 Internal Server Error: http://localhost:5000/dashboard - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:28:54,717 INFO [app] Logging system initialized
2025-09-09 11:28:54,717 INFO [app] Log level: INFO
2025-09-09 11:28:54,717 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:28:58,909 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:29:00,464 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:29:01,083 ERROR [app] Exception on /categories [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1422, in categories
    rows = conn.execute(
sqlite3.OperationalError: no such column: category_type
2025-09-09 11:29:01,086 ERROR [app] 500 Internal Server Error: http://localhost:5000/categories - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:35:32,741 INFO [app] Logging system initialized
2025-09-09 11:35:32,742 INFO [app] Log level: INFO
2025-09-09 11:35:32,742 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:35:35,844 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:35:43,547 INFO [app] POST request to categories_add from 127.0.0.1
2025-09-09 11:35:43,886 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:35:58,769 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:36:00,132 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:36:00,770 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:38:30,869 INFO [app] Logging system initialized
2025-09-09 11:38:30,870 INFO [app] Log level: INFO
2025-09-09 11:38:30,871 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:38:35,579 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:38:41,103 INFO [app] POST request to categories_add from 127.0.0.1
2025-09-09 11:38:41,359 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:38:42,503 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:38:43,932 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:38:44,693 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:38:45,084 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:40:38,377 INFO [app] User logout: gena12m@gmail.com
2025-09-09 11:40:39,031 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:40:39,790 INFO [app] POST request to login from 127.0.0.1
2025-09-09 11:40:39,790 INFO [app] Login attempt for email: gena12m@gmail.com
2025-09-09 11:40:39,791 ERROR [app] Exception on /login [POST]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 795, in login
    user = conn.execute("SELECT * FROM users WHERE email=?", (email,)).fetchone()
sqlite3.OperationalError: no such column: email
2025-09-09 11:40:39,799 ERROR [app] 500 Internal Server Error: http://localhost:5000/login - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:40:55,759 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:43:45,937 INFO [app] Logging system initialized
2025-09-09 11:43:45,938 INFO [app] Log level: INFO
2025-09-09 11:43:45,938 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:43:50,087 INFO [app] POST request to login from 127.0.0.1
2025-09-09 11:43:50,088 INFO [app] Login attempt for email: gena12m@gmail.com
2025-09-09 11:43:50,091 WARNING [app] Failed login attempt for email: gena12m@gmail.com
2025-09-09 11:43:50,144 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:43:51,060 INFO [app] POST request to login from 127.0.0.1
2025-09-09 11:43:51,061 INFO [app] Login attempt for email: gena12m@gmail.com
2025-09-09 11:43:51,061 WARNING [app] Failed login attempt for email: gena12m@gmail.com
2025-09-09 11:43:51,085 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:43:51,848 INFO [app] POST request to login from 127.0.0.1
2025-09-09 11:43:51,849 INFO [app] Login attempt for email: gena12m@gmail.com
2025-09-09 11:43:51,849 WARNING [app] Failed login attempt for email: gena12m@gmail.com
2025-09-09 11:43:51,872 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:43:54,751 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:44:04,941 INFO [app] POST request to register from 127.0.0.1
2025-09-09 11:44:04,942 INFO [app] Registration attempt for email: gena12m@gmail.com, name: ГенаDEMO
2025-09-09 11:44:05,046 INFO [app] Successful registration for user: gena12m@gmail.com (ID: 1)
2025-09-09 11:44:05,132 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:44:07,443 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:44:07,905 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:44:12,972 INFO [app] POST request to categories_add from 127.0.0.1
2025-09-09 11:44:13,315 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:44:14,185 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:45:25,098 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:45:34,302 INFO [app] POST request to expenses from 127.0.0.1
2025-09-09 11:45:34,643 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:45:37,283 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:45:44,981 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:45:47,456 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:45:57,356 INFO [app] POST request to sources_add from 127.0.0.1
2025-09-09 11:45:57,718 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:46:05,484 INFO [app] POST request to income_add from 127.0.0.1
2025-09-09 11:46:05,485 ERROR [app] Exception on /income/add [POST]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1794, in income_add
    conn.execute(
sqlite3.OperationalError: table income_daily has no column named currency
2025-09-09 11:46:05,488 ERROR [app] 500 Internal Server Error: http://localhost:5000/income/add - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:55:01,259 INFO [app] Logging system initialized
2025-09-09 11:55:01,260 INFO [app] Log level: INFO
2025-09-09 11:55:01,260 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 11:55:09,483 INFO [app] POST request to income_add from 127.0.0.1
2025-09-09 11:55:09,488 ERROR [app] Exception on /income/add [POST]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 1794, in income_add
    conn.execute(
sqlite3.IntegrityError: FOREIGN KEY constraint failed
2025-09-09 11:55:09,491 ERROR [app] 500 Internal Server Error: http://localhost:5000/income/add - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 11:55:11,655 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:12,466 INFO [app] POST request to income_add from 127.0.0.1
2025-09-09 11:55:12,492 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:23,034 INFO [app] POST request to sources_add from 127.0.0.1
2025-09-09 11:55:23,599 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:26,354 INFO [app] User logout: gena12m@gmail.com
2025-09-09 11:55:26,698 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:27,153 INFO [app] POST request to login from 127.0.0.1
2025-09-09 11:55:27,154 INFO [app] Login attempt for email: gena12m@gmail.com
2025-09-09 11:55:27,154 WARNING [app] Failed login attempt for email: gena12m@gmail.com
2025-09-09 11:55:27,182 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:28,050 INFO [app] POST request to login from 127.0.0.1
2025-09-09 11:55:28,051 INFO [app] Login attempt for email: gena12m@gmail.com
2025-09-09 11:55:28,052 WARNING [app] Failed login attempt for email: gena12m@gmail.com
2025-09-09 11:55:28,078 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:32,807 INFO [app] POST request to login from 127.0.0.1
2025-09-09 11:55:32,807 INFO [app] Login attempt for email: gena12m@gmail.com
2025-09-09 11:55:32,808 WARNING [app] Failed login attempt for email: gena12m@gmail.com
2025-09-09 11:55:32,833 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:34,586 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:46,910 INFO [app] POST request to register from 127.0.0.1
2025-09-09 11:55:46,911 INFO [app] Registration attempt for email: gena12m@gmail.com, name: ГенаDEMO
2025-09-09 11:55:47,034 INFO [app] Successful registration for user: gena12m@gmail.com (ID: 1)
2025-09-09 11:55:47,115 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:49,054 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:49,975 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:50,433 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:55:51,758 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:56:04,256 INFO [app] POST request to sources_add from 127.0.0.1
2025-09-09 11:56:04,833 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:56:09,251 INFO [app] POST request to income_add from 127.0.0.1
2025-09-09 11:56:09,889 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:56:11,217 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:56:15,071 INFO [app] POST request to categories_add from 127.0.0.1
2025-09-09 11:56:15,108 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:56:16,203 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:56:20,032 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:56:25,075 INFO [app] POST request to quick_expense from 127.0.0.1
2025-09-09 11:56:25,709 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:57:22,013 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:57:22,638 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:57:23,244 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:57:23,691 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:57:26,225 INFO [app] POST request to categories_delete from 127.0.0.1
2025-09-09 11:57:26,271 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 11:57:28,372 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 16:00:11,318 INFO [app] Logging system initialized
2025-09-09 16:00:11,319 INFO [app] Log level: INFO
2025-09-09 16:00:11,320 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 16:21:05,948 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 16:21:07,486 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 16:21:33,646 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 18:55:53,343 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 18:56:17,195 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 19:03:31,894 INFO [app] Logging system initialized
2025-09-09 19:03:31,895 INFO [app] Log level: INFO
2025-09-09 19:03:31,895 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 19:03:35,403 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 19:03:37,137 ERROR [app] Exception on /account [GET]
Traceback (most recent call last):
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/admin/crystall-budget/app.py", line 544, in _wrap
    return f(*args, **kwargs)
  File "/home/admin/crystall-budget/app.py", line 894, in account
    return render_template("account.html", user=user, currencies=CURRENCIES)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/admin/crystall-budget/templates/account.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/admin/crystall-budget/templates/base.html", line 220, in top-level template code
    {% block content %}{% endblock %}
  File "/home/admin/crystall-budget/templates/account.html", line 40, in block 'content'
    <form method="POST" action="{{ url_for('update_settings') }}" class="row g-3">
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/admin/crystall-budget/venv/lib64/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'update_settings'. Did you mean 'update_goal_progress' instead?
2025-09-09 19:03:37,142 ERROR [app] 500 Internal Server Error: http://localhost:5000/account - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
2025-09-09 19:05:10,040 INFO [app] Logging system initialized
2025-09-09 19:05:10,041 INFO [app] Log level: INFO
2025-09-09 19:05:10,041 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-09 19:05:19,221 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 19:07:06,933 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 19:07:07,810 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-09 19:07:08,693 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:03:53,907 INFO [app] Logging system initialized
2025-09-10 23:03:53,908 INFO [app] Log level: INFO
2025-09-10 23:03:53,908 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-10 23:04:10,358 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:04:13,559 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:04:15,130 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:04:24,187 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:04:30,911 INFO [app] POST request to categories_add from 127.0.0.1
2025-09-10 23:04:31,178 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:04:47,321 INFO [app] POST request to categories_add from 127.0.0.1
2025-09-10 23:04:47,572 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:04:50,956 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:05:57,945 INFO [app] POST request to sources_add from 127.0.0.1
2025-09-10 23:05:58,535 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:06:02,476 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:06:03,983 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:06:46,895 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:06:47,561 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:07:32,296 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:07:32,920 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:07:33,658 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:07:35,050 INFO [app] POST request to set_currency from 127.0.0.1
2025-09-10 23:21:20,811 INFO [app] Logging system initialized
2025-09-10 23:21:20,811 INFO [app] Log level: INFO
2025-09-10 23:21:20,811 INFO [app] Log file: /home/admin/crystall-budget/logs/crystalbudget.log
2025-09-10 23:21:23,056 INFO [app] POST request to set_currency from 127.0.0.1
